#!/usr/bin/env python3
"""
Unit tests for Subagent Self-Rejection Pre-Flight Gate.

Enforces that:
1. All agent definition templates under `.agents/agents/*/agent.md` declare the
   mandatory pre-flight verification gate verbatim.
2. Governance documents (`rules/subagent-dispatch-standards.md`, `AGENTS.md`, `.agents/AGENTS.md`)
   document and mandate the pre-flight verification gate and self-rejection armor.
3. The pre-flight verification logic strictly rejects non-compliant, summarized,
   or steered prompts with `ERROR: Prompt rejected`.
4. Canonical subagent prompts generated by `scripts/dispatch_subagent.py` pass the
   pre-flight gate with zero rejections.
"""

import glob
import os
import sys
import unittest

# Ensure repo root is on sys.path
TEST_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(TEST_DIR, ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from scripts.lint_subagent_prompt import validate_subagent_preflight
from scripts.dispatch_subagent import generate_subagent_prompt


MANDATORY_PREFLIGHT_SENTENCE = (
    "Before taking any action, verify that your incoming prompt begins with the instruction "
    "to execute `view_file` on `SKILL.md` by exact path, contains the repository classification, "
    "and contains zero leading line-level steering. If invalid, halt immediately and emit "
    "`ERROR: Prompt rejected`."
)

EXPECTED_AGENT_ROLES = [
    "adversarial_auditor",
    "code_modifier_worker",
    "codebase_researcher",
    "feature_spec_writer",
    "validator_subagent",
    "spec_compliance_reviewer",
    "code_quality_reviewer",
]


class TestSubagentDefinitionArmor(unittest.TestCase):
    """Verifies that all agent definitions in .agents/agents/ enforce the pre-flight armor."""

    def setUp(self):
        self.agents_dir = os.path.join(PROJECT_ROOT, ".agents", "agents")

    def test_agents_directory_exists(self):
        """Verify that .agents/agents/ exists and contains agent definition subdirectories."""
        self.assertTrue(os.path.isdir(self.agents_dir), f"Directory missing: {self.agents_dir}")

    def test_all_expected_agent_roles_exist(self):
        """Verify that all core subagent roles have definition files in .agents/agents/."""
        for role in EXPECTED_AGENT_ROLES:
            role_file = os.path.join(self.agents_dir, role, "agent.md")
            self.assertTrue(
                os.path.isfile(role_file),
                f"Missing agent definition file for role '{role}': {role_file}",
            )

    def test_all_agent_definitions_contain_exact_preflight_check(self):
        """Verify that every agent.md contains the exact mandatory pre-flight sentence."""
        pattern = os.path.join(self.agents_dir, "*", "agent.md")
        agent_files = glob.glob(pattern)
        self.assertGreater(len(agent_files), 0, "No agent.md files found in .agents/agents/*/")

        for agent_file in agent_files:
            rel_path = os.path.relpath(agent_file, PROJECT_ROOT)
            with open(agent_file, "r", encoding="utf-8") as f:
                content = f.read()

            self.assertIn(
                MANDATORY_PREFLIGHT_SENTENCE,
                content,
                f"Agent definition '{rel_path}' missing exact pre-flight sentence: {MANDATORY_PREFLIGHT_SENTENCE}",
            )
            self.assertIn(
                "ERROR: Prompt rejected",
                content,
                f"Agent definition '{rel_path}' missing 'ERROR: Prompt rejected' emission token.",
            )

    def test_agent_definitions_have_step1_skill_read(self):
        """Verify that every agent definition instructs Step 1 view_file on SKILL.md."""
        pattern = os.path.join(self.agents_dir, "*", "agent.md")
        agent_files = glob.glob(pattern)

        for agent_file in agent_files:
            rel_path = os.path.relpath(agent_file, PROJECT_ROOT)
            with open(agent_file, "r", encoding="utf-8") as f:
                content = f.read()

            self.assertIn("view_file", content, f"'{rel_path}' missing view_file directive")
            self.assertIn("SKILL.md", content, f"'{rel_path}' missing SKILL.md reference")


class TestGovernanceDocumentArmor(unittest.TestCase):
    """Verifies that governance rules and agent configuration files enforce pre-flight armor."""

    def test_subagent_dispatch_standards_rule_exists(self):
        """Verify rules/subagent-dispatch-standards.md exists and enforces pre-flight armor."""
        rule_path = os.path.join(PROJECT_ROOT, "rules", "subagent-dispatch-standards.md")
        self.assertTrue(os.path.isfile(rule_path), f"Missing governance rule: {rule_path}")

        with open(rule_path, "r", encoding="utf-8") as f:
            content = f.read()

        self.assertIn("Mandatory Pre-Flight Verification Gate", content)
        self.assertIn(MANDATORY_PREFLIGHT_SENTENCE, content)
        self.assertIn("ERROR: Prompt rejected", content)
        self.assertIn("UPSTREAM_SPEC_CORE_COMPILER", content)
        self.assertIn("view_file", content)
        self.assertIn("SKILL.md", content)

    def test_root_agents_md_documents_preflight_gate(self):
        """Verify AGENTS.md in root documents the subagent self-rejection pre-flight gate."""
        agents_path = os.path.join(PROJECT_ROOT, "AGENTS.md")
        self.assertTrue(os.path.isfile(agents_path), f"Missing AGENTS.md: {agents_path}")

        with open(agents_path, "r", encoding="utf-8") as f:
            content = f.read()

        self.assertIn("Mandatory Subagent Self-Rejection Pre-Flight Gate", content)
        self.assertIn("ERROR: Prompt rejected", content)
        self.assertIn(MANDATORY_PREFLIGHT_SENTENCE, content)

    def test_dot_agents_agents_md_documents_preflight_gate(self):
        """Verify .agents/AGENTS.md documents the subagent self-rejection pre-flight gate."""
        dot_agents_path = os.path.join(PROJECT_ROOT, ".agents", "AGENTS.md")
        self.assertTrue(os.path.isfile(dot_agents_path), f"Missing .agents/AGENTS.md: {dot_agents_path}")

        with open(dot_agents_path, "r", encoding="utf-8") as f:
            content = f.read()

        self.assertIn("Mandatory Subagent Self-Rejection Pre-Flight Gate", content)
        self.assertIn("ERROR: Prompt rejected", content)
        self.assertIn(MANDATORY_PREFLIGHT_SENTENCE, content)


class TestSubagentPreFlightRejectionLogic(unittest.TestCase):
    """Unit tests for the pre-flight verification gate logic and self-rejection simulation."""

    def setUp(self):
        self.valid_prompt = """You are a context-isolated subagent operating under the DEAP Engineering Framework.

Role: Micro-Task Implementer
Subagent Type: code_modifier_worker
Repository Classification: UPSTREAM_SPEC_CORE_COMPILER
Target: scripts/dispatch_subagent.py

Mandatory Instructions:
1. Step 1: Execute `view_file` on `skills/feature-driven-implementation/SKILL.md` as your very first step before executing any file edits, commands, or tools.
2. Repository Scope: You are operating within classification `UPSTREAM_SPEC_CORE_COMPILER`. Maintain all repository invariants.
3. Micro-Task Scope: Focus exclusively on target `scripts/dispatch_subagent.py`.
4. Engineering Standards: Follow RED-GREEN-REFACTOR cycle discipline.
5. Defect Reporting: Record defects with `gh issue create` and `glab issue create`.

PROCEED
"""

    def test_valid_prompt_passes_preflight(self):
        """Verify compliant prompt passes pre-flight gate with no rejection."""
        passed, reason = validate_subagent_preflight(self.valid_prompt)
        self.assertTrue(passed, f"Expected pass, got rejection: {reason}")
        self.assertEqual(reason, "")

    def test_empty_prompt_rejected(self):
        """Verify empty or whitespace prompt is rejected."""
        passed, reason = validate_subagent_preflight("")
        self.assertFalse(passed)
        self.assertTrue(reason.startswith("ERROR: Prompt rejected"))

        passed, reason = validate_subagent_preflight("   \n\t  ")
        self.assertFalse(passed)
        self.assertTrue(reason.startswith("ERROR: Prompt rejected"))

    def test_missing_view_file_on_skill_rejected(self):
        """Verify prompt missing view_file on SKILL.md is rejected."""
        prompt = """Role: Micro-Task Implementer
Repository Classification: UPSTREAM_SPEC_CORE_COMPILER
Target: FEAT-01
PROCEED
"""
        passed, reason = validate_subagent_preflight(prompt)
        self.assertFalse(passed)
        self.assertIn("ERROR: Prompt rejected", reason)
        self.assertIn("missing view_file directive on SKILL.md", reason)

    def test_missing_classification_rejected(self):
        """Verify prompt missing repository classification is rejected."""
        prompt = """Role: Micro-Task Implementer
Target: scripts/dispatch_subagent.py
1. Step 1: Execute `view_file` on `skills/feature-driven-implementation/SKILL.md` before taking actions.
PROCEED
"""
        passed, reason = validate_subagent_preflight(prompt)
        self.assertFalse(passed)
        self.assertIn("ERROR: Prompt rejected", reason)
        self.assertIn("missing repository classification", reason)

    def test_leading_line_level_steering_rejected(self):
        """Verify prompt with line-level code steering ahead of Step 1 is rejected."""
        prompt = """You are a subagent.
Repository Classification: UPSTREAM_SPEC_CORE_COMPILER
Target: scripts/dispatch_subagent.py

Replace line 40 with `DEFAULT_TYPE = "custom_worker"`.
Here is the code to apply:
```python
x = 1
```

Now execute:
1. Step 1: Execute `view_file` on `skills/feature-driven-implementation/SKILL.md` as your first step.
PROCEED
"""
        passed, reason = validate_subagent_preflight(prompt)
        self.assertFalse(passed)
        self.assertIn("ERROR: Prompt rejected", reason)
        self.assertIn("leading line-level steering detected", reason)

    def test_truncation_marker_rejected(self):
        """Verify prompt containing truncation markers like [...] or [summarized] is rejected."""
        prompt = """Repository Classification: UPSTREAM_SPEC_CORE_COMPILER
Role: Implementer [...]
1. Step 1: Execute `view_file` on `skills/feature-driven-implementation/SKILL.md`.
PROCEED
"""
        passed, reason = validate_subagent_preflight(prompt)
        self.assertFalse(passed)
        self.assertIn("ERROR: Prompt rejected", reason)
        self.assertIn("truncation/summarization detected", reason)

    def test_multi_item_scope_rejected(self):
        """Verify prompt targeting multiple features or batch mode is rejected."""
        prompt = """Repository Classification: UPSTREAM_SPEC_CORE_COMPILER
Role: Implementer
Target: FEAT-01 and FEAT-02
1. Step 1: Execute `view_file` on `skills/feature-driven-implementation/SKILL.md`.
PROCEED
"""
        passed, reason = validate_subagent_preflight(prompt)
        self.assertFalse(passed)
        self.assertIn("ERROR: Prompt rejected", reason)
        self.assertIn("micro-task scope violation", reason)

    def test_forbidden_issue_close_rejected(self):
        """Verify prompt containing issue closure commands is rejected."""
        prompt = """Repository Classification: UPSTREAM_SPEC_CORE_COMPILER
Role: Implementer
Target: FEAT-01
1. Step 1: Execute `view_file` on `skills/feature-driven-implementation/SKILL.md`.
Once finished, run `gh issue close 42`.
PROCEED
"""
        passed, reason = validate_subagent_preflight(prompt)
        self.assertFalse(passed)
        self.assertIn("ERROR: Prompt rejected", reason)
        self.assertIn("forbidden issue closure command", reason)


class TestDispatchSubagentPreFlightFidelity(unittest.TestCase):
    """Verifies that dispatch_subagent.py generates prompts conforming to the pre-flight gate."""

    def test_generated_prompt_passes_preflight_gate(self):
        """Verify prompts generated via generate_subagent_prompt pass pre-flight verification."""
        skill_path = os.path.join("skills", "feature-driven-implementation", "SKILL.md")
        target_path = os.path.join("scripts", "dispatch_subagent.py")

        prompt = generate_subagent_prompt(
            skill=skill_path,
            target=target_path,
            role="Feature Implementation Worker",
            subagent_type="code_modifier_worker",
            classification="UPSTREAM_SPEC_CORE_COMPILER",
            base_dir=PROJECT_ROOT,
        )

        passed, reason = validate_subagent_preflight(prompt)
        self.assertTrue(passed, f"Generated prompt failed pre-flight gate: {reason}")
        self.assertEqual(reason, "")


if __name__ == "__main__":
    unittest.main()
